---
- name: Install Home Assistant on Ubuntu 24.04
  hosts: localhost
  become: yes

  tasks:
    - name: Update APT package index
      apt:
        update_cache: yes

    - name: Install required system packages
      apt:
        name:
          - python3
          - python3-venv
          - python3-pip
          - libffi-dev
          - libssl-dev
          - libjpeg-dev
          - zlib1g-dev
          - autoconf
          - build-essential
          - libopenjp2-7
          - libturbojpeg0-dev
          - libtiff-dev   # Geändertes Paket
          - tzdata
        state: present

    - name: Create a user for Home Assistant
      user:
        name: homeassistant
        system: yes
        create_home: yes
        shell: /bin/bash

    - name: Create Home Assistant directory
      file:
        path: /srv/homeassistant
        state: directory
        owner: homeassistant
        group: homeassistant

    - name: Create a virtual environment for Home Assistant
      command: python3 -m venv /srv/homeassistant
      become_user: homeassistant

    - name: Upgrade pip to the latest version
      pip:
        name: pip
        state: latest
        executable: /srv/homeassistant/bin/pip
      become_user: homeassistant

    - name: Install Home Assistant
      pip:
        name: homeassistant
        virtualenv: /srv/homeassistant
        virtualenv_command: /srv/homeassistant/bin/python3
      become_user: homeassistant

    - name: Create systemd service for Home Assistant
      copy:
        dest: /etc/systemd/system/home-assistant@homeassistant.service
        content: |
          [Unit]
          Description=Home Assistant
          After=network-online.target

          [Service]
          Type=simple
          User=homeassistant
          ExecStart=/srv/homeassistant/bin/hass -c "/home/homeassistant/.homeassistant"
          Restart=on-failure

          [Install]
          WantedBy=multi-user.target
      notify: Restart Home Assistant

    - name: Enable and start Home Assistant service
      systemd:
        name: home-assistant@homeassistant
        enabled: yes
        state: started

  handlers:
    - name: Restart Home Assistant
      systemd:
        name: home-assistant@homeassistant
        state: restarted
