- name: Install Packages 
  apt:
     name:
         - python3
          - python3-venv
          - python3-pip
          - libffi-dev
          - libssl-dev
          - libjpeg-dev
          - zlib1g-dev
          - autoconf
          - build-essential
          - libopenjp2-7
          - libturbojpeg0-dev
          - libtiff-dev   # Geändertes Paket
          - tzdata
     state: present
